export const USER_ACTION_TYPES = {
  GET_USER_DETAIL: 'GET_USER_DETAIL',
  GET_USER_LIST_BRIEF: 'GET_USER_LIST_BRIEF',
  // FETCH_AUTHORIZE_USER: "FETCH_AUTHORIZE_USER",
  GET_USER_LIST: 'GET_USER_LIST',
  GET_USER_TEAMS: 'GET_USER_TEAMS',
}

export const NONWORKINGDAY_ACTION_TYPES = {
  ADD_NON_WORKING_DAY: 'ADD_NON_WORKING_DAY',
  GET_NON_WORKING_DAYS: 'GET_NON_WORKING_DAYS',
  UPDATE_NON_WORKING_DAYS: 'UPDATE_NON_WORKING_DAYS',
  GET_NON_WORKING_DAYS_RANGE: 'GET_NON_WORKING_DAYS_RANGE',
}

export const TEAMS_ACTION_TYPES = {
  GET_TEAMS_LIST: 'GET_TEAMS_LIST',
  GET_TEAMS_LIST_V2: 'GET_TEAMS_LIST_V2',
  UPDATE_DEFAULT_TEAM: 'UPDATE_DEFAULT_TEAM',
}

export const TIME_SHEET_ACTION_TYPES = {
  GET_TIME_SHEET: 'GET_TIME_SHEET',
  UPDATE_TIME_SHEET: 'UPDATE_TIME_SHEET',
} as const

export const COMMON_ACTION_TYPES = {
  REQUEST: '_REQUEST',
  SUCCESS: '_SUCCESS',
  ERROR: '_ERROR',
  CLEAR: '_CLEAR',
  SET_ALERT_REQ: '_SET_ALERT_REQ',
  SET_ALERT: '_SET_ALERT',
  CLEAR_ALERT: '_CLEAR_ALERT',
}

export const TIME_ENTRY_ACTION_TYPES = {
  MANAGE_TIME_ENTRY_DETAIL: 'MANAGE_TIME_ENTRY_DETAIL',
  GET_TIME_ENTRY_DETAIL: 'GET_TIME_ENTRY_DETAIL',
  GET_TEAM_DETAIL: 'GET_TEAM_DETAIL',
  UPDATE_TIME_ENTRY_DETAIL: 'UPDATE_TIME_ENTRY_DETAIL',
  SET_EDITING_RECORD: 'SET_EDITING_RECORD',
  EDIT_TIME_ENTRY: 'EDIT_TIME_ENTRY',
}

// V2
export const ATTENDANCE_ACTION_TYPES = {
  ADD_ATTENDANCE_INFO: 'ADD_ATTENDANCE_INFO',
  GET_ATTENDANCE_INFO: 'GET_ATTENDANCE_INFO',
}

export const CONFIG_EMAIL_ADDRESSES_ACTION_TYPES = {
  ADD_CONFIG_EMAIL_ADDRESSES_DETAIL: 'ADD_CONFIG_EMAIL_ADDRESSES_DETAIL',
  GET_CONFIG_EMAIL_ADDRESSES_DETAIL: 'GET_CONFIG_EMAIL_ADDRESSES_DETAIL',
  UPDATE_CONFIG_EMAIL_ADDRESSES_DETAIL: 'UPDATE_CONFIG_EMAIL_ADDRESSES_DETAIL',
}

export const NWDAY_CAL_ACTION_TYPES = {
  GET_NON_WORKING_DAYS: 'GET_NON_WORKING_DAYS',
  GET_NON_WORKING_DAYS_RANGE: 'GET_NON_WORKING_DAYS_RANGE',
}

export const LEAVE_ACTION_TYPES = {
  ADD_LEAVE: 'ADD_LEAVE',
  GET_LEAVES_OF_USER: 'GET_LEAVES_OF_USER',
  GET_LEAVES: 'GET_LEAVES',
  UPDATE_LEAVE_STATUS: 'UPDATE_LEAVE_STATUS',
  GET_POINT_PERSON_LIST: 'GET_POINT_PERSON_LIST',
  // v2
  GET_LEAVE_LIST: 'GET_LEAVE_LIST',
  UPDATE_LEAVE: 'GET_LEAVE',
  GET_LEAVE_COUNT: 'GET_LEAVE_COUNT',
  ADD_LEAVE_COUNT: 'ADD_LEAVE_COUNT',
  UPDATE_LEAVE_COUNT: 'UPDATE_LEAVE_COUNT',
  GET_LEAVE_COUNT_SUMMARY: 'GET_LEAVE_SUMMARY',
  GET_USER_LEAVE_INFO: 'GET_USER_LEAVE_INFO',
  UPDATE_USER_LEAVE_STATUS: 'UPDATE_USER_LEAVE_STATUS',
}

export const ABSENTEEISM_REPORT_ACTION_TYPES = {
  GET_ABSENTEEISM_DETAIL: 'GET_ABSENTEEISM_DETAIL',
  RESET_ABSENTEEISM_DETAIL: 'RESET_ABSENTEEISM_DETAIL',
}

export const CLIENT_ACTION_TYPES = {
  GET_CLIENT_LIST: 'GET_CLIENT_LIST',
}

export const REPORT_ACTION_TYPES = {
  GET_ATTENDANCE_REPORT: 'GET_ATTENDANCE_REPORT',
  RESET_ATTENDANCE_DETAIL: 'RESET_ATTENDANCE_DETAIL',
  GET_USER_CLIENT_HIERARCHY: 'GET_USER_CLIENT_HIERARCHY',
  GET_ANNUAL_DETAILED_LEAVES_INFO: 'GET_ANNUAL_DETAILED_LEAVES_INFO',
  GET_SBU_LIST: 'GET_SBU_LIST',
  POST_EXCEPTION_ATTENDANCE: 'POST_EXCEPTION_ATTENDANCE',
  GET_EXCEPTION_ATTENDANCE: 'GET_EXCEPTION_ATTENDANCE',
  GET_EXCEPTION_ATTENDANCE_DOWNLOAD: 'GET_EXCEPTION_ATTENDANCE_DOWNLOAD',
  GET_TIME_ENTRY_REPORT: 'GET_TIME_ENTRY_REPORT',
  POST_TIME_ENTRY: 'POST_TIME_ENTRY',
  GET_TIME_ENTRY_DOWNLOAD: 'GET_TIME_ENTRY_DOWNLOAD',
}

export const DETAILED_ATTENDANCE_REPORT_ACTION_TYPES = {
  GET_DETAILED_ATTENDANCE_DETAIL: 'GET_DETAILED_ATTENDANCE_DETAIL',
  RESET_DETAILED_ATTENDANCE_DETAIL: 'RESET_DETAILED_ATTENDANCE_DETAIL',
}

export const ATTENDANCE_SUMMARY_REPORT_ACTION_TYPES = {
  GET_ATTENDANCE_SUMMARY_DETAIL: 'GET_ATTENDANCE_SUMMARY_DETAIL',
  RESET_ATTENDANCE_SUMMARY_DETAIL: 'RESET_ATTENDANCE_SUMMARY_DETAIL',
  GET_ATTENDANCE_SUMMARY_PROJECT_WISE_DETAIL: 'GET_ATTENDANCE_SUMMARY_PROJECT_WISE_DETAIL',
}

export const ALLOCATION_ACTION_TYPES = {
  GET_ALLOCATIONS: 'GET_ALLOCATIONS',
}
export const AUTH_ACTION_TYPES = {
  AUTHORIZE_USER: 'AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER: 'FETCH_AUTHORIZE_USER',
  FETCH_AUTHORIZE_USER_ROLES: 'FETCH_AUTHORIZE_USER_ROLES',
  SET_ACTIVE_USER_ROLE: 'SET_ACTIVE_USER_ROLE',
  FETCH_ACTIVE_USER_ROLE: 'FETCH_ACTIVE_USER_ROLE',
  LOGOUT: 'LOGOUT',
}
