export const APP_TABLE_CONFIGS = {
  DEFAULT_ROWS_PER_PAGE_OPTIONS: [10, 25],
  DEFAULT_ROWS_PER_PAGE: 10,
}
export enum BROWSER_STORAGE_CONFIGS {
  MAX_COOKIE_SIZE = 4000,
  MAX_LOCAL_STORAGE_SIZE = 4.5e6,
}
export const TIME_ENTRY_LOCATION_IDS = {
  WORK_FROM_HOME: 1,
  WORK_FROM_OFFICE: 2,
}
export const TIME_ENTRY_TYPES = {
  START: 1,
  START_END: 2,
}

export enum APPLICATION_IDS {
  HERA = 4,
  ATHENA = 2,
  HERMES = 1,
  DASHBOARD = 5,
  DEMETER = 6,
}

export const ALERT_CONFIGS = {
  TIMEOUT: 4000,
  ASYNC_REQ_TIMEOUT: 2000,
  AUTO_CLEAR: true,
}

export const USER_ROLE_ID = {
  SUPER_ADMIN: 1,
  HR_PERSONNEL: 5,
  INTERNAL_SUPERVISOR: 6,
  EMPLOYEE: 4,
  ALL_USER_ROLES: -1,
}
export const LEAVE_STATUS_IDS = {
  APPLIED: 1,
  APPROVED: 2,
  REJECTED: 3,
  DISABLED: 4,
}

export const LEAVE_TYPE_IDS = {
  ANNUAL: 1,
  LIEU: 2,
  CASUAL: 3,
}

export const DEFAULT_SELECTED_LEAVE_TYPE = 3
export enum APP_FEATURE_KEYS {
  // employee
  VIEW_OWN_TIME_ENTRIES = 'FE021',
  CREATE_UPDATE_OWN_TIME_ENTRY = 'FE023',
  VIEW_OWN_LEAVES = 'FE025',
  CREATE_UPDATE_OWN_LEAVE = 'FE027',
  CONFIGURE_OWN_DEFAULT_TEAM = 'FE035',
  VIEW_OWN_ALLOCATION = 'FE005',
  VIEW_OWN_LEAVE_SUMMERY = 'FE065',
  UPDATE_OWN_TIME_SHEET = 'FE134',

  // internal supervisor
  VIEW_TEAMS_LEAVES = 'FE064',

  //common
  ATHENA_ABSENTEEISM_REPORT = 'FE029',
  ATHENA_ATTENDANCE_REPORT = 'FE030',
  USER_PROFILE = 'FE061',
  APPROVE_REJECT_LEAVES = 'FE062',
  VIEW_ALL_LEAVES_SUMMERY = 'FE066',
  VIEW_ALL_TIME_ENTRIES = 'FE020',
  CREATE_UPDATE_ALL_TIME_ENTRY = 'FE022',
  VIEW_ALL_LEAVES = 'FE024',
  CREATE_UPDATE_ALL_LEAVE = 'FE026',
  UPDATE_LEAVE_COUNT_CONFIGURATION = 'FE028',
  VIEW_LEAVE__COUNT_CONFIGURATION = 'FE063',
  ATHENA_DETAILED_ATTENDANCE_REPORT = 'FE031',
  ATHENA_ATTENDANCE_SUMMARY_REPORT = 'FE032',
  ATHENA_ANNUAL_LEAVE_REPORT = 'FE033',
  ATHENA_EXCEPTION_REPORT = 'FE132',
  ATHENA_TIME_ENTRY_REPORT = 'FE138',

  //super admin
  MANAGE_HOLIDAY_CALENDAR = 'FE034',
  VIEW_ALL_USERS = 'FE036',
}

export const DATE_FORMAT = 'YYYY-MM-DD'
export const DATE_FORMAT_2 = 'Do MMM of YYYY'
export const DATE_TIME_FORMAT = 'YYYY-MM-DD - HH:mm:ss'

export enum EXCEPTION_REPORT_STATUS {
  COMPLETED = 'COMPLETED',
  INPROGRESS = 'IN-PROGRESS',
  ERROR = 'ERROR',
}

export enum TIME_ENTRY_DATE_TYPES {
  DEFAULT = 0,
  WEEKEND = 1,
  FULL_NON_WORKING = 2,
  HALF_NON_WORKING = 3,
  DISABLED = 4,
  FUTURE_DATE,
}

export enum TIME_ENTRY_LEAVE_TYPES {
  DEFAULT = 0,
  FULL_DAY_APPLIED = 1,
  FULL_DAY_APPROVED = 2,
  HALF_DAY_APPLIED = 3,
  HALF_DAY_APPROVED = 4,
}
