export enum APP_ROUTES {
  ROOT = '/',
  DASHBOARD = '/dashboard',
  ADD_ATTENDANCE = '/add-attendance',
  NON_WORKING_DAYS = '/non-working-days',
  MARKING_LEAVE = '/marking-leave',
  MARKING_LEAVE_HR = '/marking-leave-hr',
  EDIT_TIME_ENTRY = '/edit-time-entry',
  ABSENTEEISM_REPORT = '/absenteeism-report',
  ATTENDANCE_REPORT = '/attendance-report',
  LEAVE_MANAGEMENT = '/leave-management',
  LEAVE_CONFIGURATION = '/leave-configuration',
  SUPERVISOR_LEAVE_ACTIONS = '/approve-leave',
  USER_PROFILE = '/user-profile',
  DETAILED_ATTENDANCE_REPORT = '/detailed-attendance-report',
  ATTENDANCE_SUMMARY_REPORT = '/attendance-summary',
  ANNUAL_DETAILED_LEAVE_REPORT = '/annual-detailed-leave-report',
  EXCEPTION_ATTENDANCE_REPORT = '/exception-attendance-report',
  MANAGE_TIME_ENTRIES = '/manage-time-entries',
  TIME_ENTRY_REPORT = '/time-entry-report',
}
